### ISSUE TITLE
Sequences couldn't be created for MSSQL

### ISSUE THREAD

**Issue by imorenov94** [Haulmont/jmix-data#112]
bomVersion = '1.2.0-SNAPSHOT'

**Steps:**
1. Create Project
2. Change DB to MSSQL Server 2008 or 2012+
3. Create an entity with id type "Integer" and without "Has UUID" in the list of traits
4. Update annotation for entity by the same way ```@JmixGeneratedValue(sequenceName = "test") ```
4. Create screens for entity
5. Run the app and create an instance of the entity
6. Check that DB contains a sequence as a new table with a specified sequence name from ```@JmixGeneratedValue``` for MSSQL Server 2008 or record in "sys.sequences" in case you chose MSSQL Server 2012+ 

**AR:** Sequence hasn't been created for both versions MSSQL server

**Comment by gorbunkov** [comment]
@imorenov94 just tried and the sequence has been successfully created in the database. I'm using  Could you please check again?

**Comment by imorenov94** [comment]
It works for me too... I'll close this issue
