### ISSUE TITLE
Use some default fetchPlan in case nested attribute of the dataContainer has no fetch-plan associated

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-data#121]
### Scenario

In relation to this issue in Jmix Studio: https://youtrack.haulmont.com/issue/JST-2582

When there is no fetchPlan set in the attribute of the data container like this (via XML):

```xml
<instance id="productDc"
                  class="de.diedavids.jmix.rys.product.Product">
    <fetchPlan extends="_base">
        <property name="prices"/>
    </fetchPlan>
    <loader/>
    <collection id="pricesDc" property="prices"/>
</instance>
```

Here `<property name="prices"/>` misses `fetchPlan="someFetchPlan"`. It is unspecified what is loaded in this scenario. Apperently neither `_base` nor `_instance_name` is used. Instead no attributes are loaded.

### Improvement

When not adding any fetch plan to the XML (or programmatically), there should be a default fetch plan that is used. Probably it should be the `_base` fetch plan, since it is most likely that the this fetch plan is considered to be the "default".

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
