### ISSUE TITLE
Application fails to start if additional datastore has no entities

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-data#27]
#### Steps
1. Create new Jmix-project
2. Create additional datastore
3. Run project
**ER:** project starts without problems
**AR:** `java.lang.IllegalArgumentException: Cannot parse persistence unit from class path resource [com/company/untitled1/test1-persistence.xml]`

#### Cause:
Jmix gradle plugin doesn't know about additional datastores and cannot create  appropriate `*-persistence.xml` if there is no entity related to datastore.

#### Proposed solution:
Ignore absent additional `*-persistence.xml` and setup persistence unit settings from code instead (if need)

**Comment by maistrenkoIulia** [comment]
v. 0.3 -snapshot

TC: create project>create additional datastorages (hsql, postgres)
Er: the project should built successfully
AR:
```
'JmixEntityManagerFactoryBean(java.lang.String, javax.sql.DataSource, org.springframework.orm.jpa.JpaVendorAdapter, io.jmix.data.persistence.DbmsSpecifics, io.jmix.core.JmixModules, io.jmix.core.Resources)' in 'io.jmix.data.impl.JmixEntityManagerFactoryBean' cannot be applied to '(java.lang.String, javax.sql.DataSource, org.springframework.orm.jpa.JpaVendorAdapter, io.jmix.data.persistence.DbmsSpecifics, io.jmix.core.JmixModules)'
```

[second.zip](https://github.com/Haulmont/jmix-data/files/5836188/second.zip)

**Comment by dtaimanov** [comment]
> v. 0.3 -snapshot
> 
> TC: create project>create additional datastorages (hsql, postgres)
> Er: the project should built successfully
> AR:
> 
> ```
> 'JmixEntityManagerFactoryBean(java.lang.String, javax.sql.DataSource, org.springframework.orm.jpa.JpaVendorAdapter, io.jmix.data.persistence.DbmsSpecifics, io.jmix.core.JmixModules, io.jmix.core.Resources)' in 'io.jmix.data.impl.JmixEntityManagerFactoryBean' cannot be applied to '(java.lang.String, javax.sql.DataSource, org.springframework.orm.jpa.JpaVendorAdapter, io.jmix.data.persistence.DbmsSpecifics, io.jmix.core.JmixModules)'
> ```
> 
> [second.zip](https://github.com/Haulmont/jmix-data/files/5836188/second.zip)

@maistrenkoIulia , please make `<StoreName>StoreConfiguration.java` look like:
```
//...
import io.jmix.core.Resources;

//...

    @Bean
    LocalContainerEntityManagerFactoryBean <storename>EntityManagerFactory(JpaVendorAdapter jpaVendorAdapter, DbmsSpecifics dbmsSpecifics, JmixModules jmixModules, Resources resources) {
        return new JmixEntityManagerFactoryBean("<storename>", <storename>DataSource(), jpaVendorAdapter, dbmsSpecifics, jmixModules, resources);
    }
//...
```
or wait for studio update and recreate additional datastore then

**Comment by maistrenkoIulia** [comment]
fixed in platform
issue in studio - https://youtrack.haulmont.com/issue/JST-572
