### ISSUE TITLE
Compatibility with JTA global transactions

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-data#30]
#### Progress
2021-04-13: 15%
2021-04-19: 25%
2021-04-26: 40%
2021-05-11: 70%
2021-05-17: 85%
2021-05-24: 90%

- [x] Investigate possible JTA configurations
- [x] Check events and synchronisations
- [x] Investigate possible implementations
- [x] Create some kind of API
- [x] Test coverage
- [x] Dependencies and starters

**Comment by andreysubbotin** [comment]
Sample project: https://github.com/jmix-projects/jta-demo
QA notes: 
- Test CRUD operations using UI on JTA additional stores: `orders` and `main store`
- Try to run the JTA integration test `com.company.jtatest.GlobalTxTest` from IntelliJIdea
