### ISSUE TITLE
Cannot fetch reference attribute without explicit fetch plan in Many-To-Many case

### ISSUE THREAD

**Issue by artemy63** [Haulmont/jmix-data#31]
As presented Jmix should provide extracting references from entity even if there is no any fetch plan exactly specified, but in my case when using Many-To-Many relation I've got 
```IllegalStateException: Cannot get unfetched attribute [users] from detached object com.company.fetchplantest.entity.UserGroup-9314af20-5d49-69be-2be2-07a85999647f [detached].```

Definition of entity
```
@JmixEntity
@Table(name = "TEST_USER_GROUP")
@Entity(name = "test_UserGroup")
public class UserGroup {
    @JoinTable(name = "FETCHPLANTEST_USER_GROUP_USER_LINK",
            joinColumns = @JoinColumn(name = "USER_GROUP_ID"),
            inverseJoinColumns = @JoinColumn(name = "USER_ID"))
    @ManyToMany
    private List<User> users;
```

user-group-edit descriptor
```
    <data>
        <instance id="userGroupDc"
                  class="com.company.fetchplantest.entity.UserGroup">
            <fetchPlan extends="_local"/>
            <loader/>
            <collection id="usersDc" property="users"/>
        </instance>
    </data>
```

Please take a look, simple test project in attach
[fetchplantest.zip](https://github.com/Haulmont/jmix-data/files/5733717/fetchplantest.zip)

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-data#19
