### ISSUE TITLE
Data from nested instance name is not displayed

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-data#52]
1.0.0-SNAPSHOT

1. Open project [detachh.zip](https://github.com/Haulmont/jmix-data/files/6062261/detachh.zip)
2. Run the app
3. Open Schedule browser
4. Create one

ER: instance names should be correct
AR: the Lesson field is detached (Teacher part)
Editor:
![image](https://user-images.githubusercontent.com/73226373/109510422-6bbdb580-7abb-11eb-9834-de6c34cf2967.png) 
Browser:
![image](https://user-images.githubusercontent.com/73226373/109510393-62cce400-7abb-11eb-9276-bf1ecc97a277.png)

Lesson get instance name method:
```
    @InstanceName
    @DependsOnProperties({"teacher", "subject"})
    public String getInstanceName() {
        return String.format("%s %s", teacher, subject);
    }
```
Teacher get instance name method:
```
    @InstanceName
    @DependsOnProperties({"firstName", "lastName"})
    public String getInstanceName() {
        return String.format("%s %s", firstName, lastName);
    }
```

**Comment by andreysubbotin** [comment]
Hi @lovtsovaik,  is there an annotation ` @InstanceName` on methods?

**Comment by lovtsovaik** [comment]
@andreysubbotin yes, of course, I updated the ticket text

**Comment by andreysubbotin** [comment]
``` 
@InstanceName
@DependsOnProperties({"teacher", "subject"})
 public String getInstanceName() {
        return String.format("%s %s", teacher, subject);
 }
```
This kind of method uses `Teacher.toString()` for instance name formating, so the result on a screen is correct.

You can use `InstanceNameProvider` or `MetadataTools` for instance name formatting:
```
@InstanceName
@DependsOnProperties({"teacher", "subject"})
 public String getInstanceName(MetadataTools metataTools) {
        return String.format("%s %s", metadataTools.getInstanceName(teacher), subject);
 }
```
