### ISSUE TITLE
Unexpected error occurs when creating an entity generated from MSSQL database

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-data#54]
bomVersion = '1.0.0-SNAPSHOT'

For QA: check also case from https://github.com/Haulmont/jmix-data/issues/56
1. Connect to MSSQL server using a third-party program and execute sql script instnwnd.sql from https://github.com/microsoft/sql-server-samples/tree/master/samples/databases/northwind-pubs (or use already created database Northwind in company server)
2. Create data store and connect it to this database
3. Click Generate model, refresh list
4. Select Region -> Next -> Next -> Finish
5. Run the app (ignore all changelogs in this database if it appears)
6. Open Region browser
7. Click Create
8. Put some string to Region description
9. Click OK

AR: Unexpected error occurs
SQLServerException: Violation of PRIMARY KEY constraint 'PK_Region'. Cannot insert duplicate key in object 'dbo.Region'. The duplicate key value is (1).
```
com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK_Region'. Cannot insert duplicate key in object 'dbo.Region'. The duplicate key value is (1).
```
see stacktrace [SQLServerException.txt](https://github.com/Haulmont/jmix-data/files/6123176/SQLServerException.txt)

If you generate a creation script and use it to create a new table, then there is no such error for the generated new entity.
Therefore, it is not a matter of defining the table, but of constraints, keys, and so on.

Sample project: [testlqpreview.zip](https://github.com/Haulmont/jmix-data/files/6123221/testlqpreview.zip)

ER: create an entity without errors

#### Cause
Sequences are not generated for entity, so Integer/Long ids for new entities have the same values as in existed records, that leads to conflict.

#### Possible solutions
1. Generate sequences too. 
Potential problem: sequence name is built by entity name and becomes invalid in case of changing entity metaclass name or creating ancestor entity using the same table. 
Solution: Set sequence name explicitly in `@JmixGeneratedValue#sequenceName` (seems to be not working now, migrate this feature from CUBA)
2. Provide instrument for sequence generation by entity and existing data in database.
3. Propose to select one of existing sequences

**Comment by knstvk** [comment]
Setting `@JmixGeneratedValue#sequenceName` to an existing sequence should work. If it doesn't, create an issue for this particular problem.
