### ISSUE TITLE
UniqueConstraintViolation is not handled when using hibernate datastore

### ISSUE THREAD

**Issue by IskandarovRost** [Haulmont/jmix-data#55]
linked to # 32

1) Create an entity with a unique attribute
2) Create Backoffice CRUD Screens for it
3) Create a couple of instances with the same value of the unique attribute
* Eclipselink Starter
* Hibernate Starter

**AR:** With Eclipselink the exception is handled
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/204d454b-18f8-4643-bf2e-30c177472d50)

And with Hibernate - not
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/df8398bd-e0c6-4f38-ace8-4940b0e7ffe6)

**Comment by DartVerder** [comment]
Exception is handled for Eclipselink and Hibernate data stores
![image](https://user-images.githubusercontent.com/69783839/113126937-3bd41000-9229-11eb-9bb0-09a2efa2034b.png)
