### ISSUE TITLE
Query by condition is not cached

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-data#63]
- Run attached project
- Open Users browser
- Click Test 3 button. It executes the following:
  
  ```
  dataManager.load(User.class)
                .condition(PropertyCondition.contains("username", "u"))
                .cacheable(true)
                .list()
  ```

- See SQL log messages - the query is executed against DB
- Click Test 3 button again
ER: query is cached, no SQL messages
AR: the query is executed against DB again

[https://app.zenhub.com/files/285283915/8ac586e5-bcdb-4c38-9df3-531eeec5a2ae/download](https://app.zenhub.com/files/285283915/8ac586e5-bcdb-4c38-9df3-531eeec5a2ae/download)

**Comment by andreysubbotin** [comment]
Property condition generates different JPQL expressions each time.
