### ISSUE TITLE
Support for relative date and time moments in JPQL queries

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-data#64]
At least the following:
- First and last days of the current year/month/week
- Start and end of the current day (00:00:00 и 23:59:59)
- Start of the last and next days (00:00:00)
- Start and end of the current hour (00:00 и 59:59)
- Start and end of the current minute

Task description in the documentation: https://youtrack.haulmont.com/articles/PLAT-A-128/Relative-date-and-time-moments-in-JPQL-queries

## Definition

The approach is adding a new constant (as exist JPQL constants - CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP):

FIRST_DAY_OF_CURRENT_YEAR
LAST_DAY_OF_CURRENT_YEAR
FIRST_DAY_OF_CURRENT_MONTH
LAST_DAY_OF_CURRENT_MONTH
FIRST_DAY_OF_CURRENT_WEEK
LAST_DAY_OF_CURRENT_WEEK
START_OF_CURRENT_DAY
END_OF_CURRENT_DAY
START_OF_YESTERDAY
START_OF_TOMORROW
START_OF_CURRENT_HOUR
END_OF_CURRENT_HOUR
START_OF_CURRENT_MINUTE
END_OF_CURRENT_MINUTE

User's queries can use the constants. Before executing queries constants will be replaced to the current date&time moment. 

Example: 
User's query
`SELECT * FROM USER u WHERE u.createdDate > FIRST_DAY_OF_YEAR`
after replacing
`SELECT * FROM USER u WHERE u.createdDate > '2021-01-01'`

## Progress

2021-04-14: 80%

Parts of task:

- [x] Define a view (article in the knowledge base)
- [x] Create a mockup for adding into filters (article in the knowledge base)
- [x] Implement view in code
- [x] Write tests
- [x] Code review
- [ ] QA

**Comment by DartVerder** [comment]
```
START_OF_CURRENT_HOUR,
END_OF_CURRENT_HOUR,
START_OF_CURRENT_MINUTE,
END_OF_CURRENT_MINUTE
```
works incorrectly, uses a limit in seconds from the current time  -> so for example, hh:00:00 is not processed as the start of the hour, hh:59:59  is not processed as the end of the hour (while current time != hh:mm:59)
