### ISSUE TITLE
After the application is launched, the Time fields change their type to Date

### ISSUE THREAD

**Issue by TikhomirovME** [Haulmont/jmix-data#71]
Platform V version: 0.9.1
Platform V Studio plugin version: 1.0.SNAPSHOT96-211
IntelliJ version: IntelliJ IDEA 2021.1 (Ultimate Edition)

Steps:

Create an entity with the Time attribute
Launch the app
Open the entity editor in the backoffice UI

Expected result:
The browser displays a field with a placeholder and a Time mask
In the Idea, the field type remained Time

Actual result:
The browser displays a field with a placeholder and a Date mask
In the Idea, the field type changed to Date

**Comment by alexbudarov** [comment]
According to description, it looks like Studio bug, isn't it?
