### ISSUE TITLE
NPE in DataManager when trying to load KV entity

### ISSUE THREAD

**Issue by belyaev-andrey** [Haulmont/jmix-data#75]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3028-211
IntelliJ version: IntelliJ IDEA 2021.1.2 (Ultimate Edition)

**STR**:
* Create "Task" entity and make an M:O association with "User"
* Create Browser and Editor screens for the "Task"
* Create `@Component` with the method that returns `User`:`findUser`. See the code in the attachment.
* Create `onInitEntity` handler in Task Editor and try to fill the reference field with the method invocation result

**ER**: 
The method returns something

**AR**: 
NullPointerException appears

Even the simplest query like 
```java
dataManager.loadValues("select u from User u").properties("user").list();
```
causes NPE

Attachement: [NPE-jmix-test.zip](https://github.com/Haulmont/jmix-data/files/6642505/NPE-jmix-test.zip)

**Comment by lovtsovaik** [comment]
1.0.0-SNAPSHOT - ok,
1.1.0-SNAPSHOT - ok
