### ISSUE TITLE
Loading of EmbeddedId property fails

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [Haulmont/jmix-data#76]
We have entity 'CompositeKeyEntity' with EmbeddedId property 'id' related to Embeddable entity 'CompositeKey' and want to select collection of 'CompositeKey' instances.

Within JmixEclipseLinkQuery query 'select e.id from CompositeKeyEntity e' is transformed into irrelevant query 'select tempEntityAlias from CompositeKey tempEntityAlias, CompositeKeyEntity e where tempEntityAlias.id = e.id.id'.

**Comment by artemglinov** [comment]
###  **QA Notes**

JmixEclipseLinkQuery is an extended Jmix implementation of javax.persistence.TypedQuery interface. It provides performing various manipulations with JPQL-queries. For example, it is possible to obtain a query result list of entities by means of following calls:
`entityManager.createQuery("select e from CompositeKeyEntity e", CompositeKeyEntity.class).getResultList()`, 
where `entityManager` is injected as 
`@PersistenceContext
private EntityManager entityManager;`.
