### ISSUE TITLE
Unique constraint validation error during creating entity if association entity has composite key 

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-data#97]
**Environment:**
Jmix version: 1.1.0
Jmix Studio plugin version: 1.1.SNAPSHOT3752-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
OS: Ubuntu 20.04 LTS
DB: PostgreSQL 9.4

TC:
1. Create Create database with name `additds` in Postgres and add a table with composite PK:
```
create table foo(key1 varchar, key2 varchar, name varchar);
alter table foo add constraint pk_foo primary key (key1, key2);
```
2. Open attached project
3. Run app -> Login as admin
4. Open Foos -> Create new instance with values:
- Key1 - qwe
- Key2 - rty
- Name - name1
5. Create another Foo  instance with values:
- Key1 - qwee
- Key2 - rty
- Name - name2
6. Open Bars -> Create new instance with values:
- Name - name1
- Foo - name1
7. Create another Bar instance with values:
- Name - name2
- Foo - name2 -> Try to save

**AR:**
![image](https://user-images.githubusercontent.com/45730069/141273385-fbf3eadd-6777-4b9a-90c7-70974b5e689f.png)

```
2021-11-11 13:28:41.979  WARN 170792 --- [nio-8080-exec-2] eclipselink.logging.all                  : Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.9.4-jmix): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uc_bar_foo_id_key1"
  Detail: Key (foo_id_key1)=(qwe) already exists.
Error Code: 0
Call: INSERT INTO BAR (ID, NAME, FOO_ID_KEY1, FOO_ID_KEY2) VALUES (?, ?, ?, ?)
	bind => [c7ae4142-9e22-089b-23b6-7d0ee2544ec5, name2, qwe, erty]
Query: InsertObjectQuery(com.company.post1.entity.Bar-c7ae4142-9e22-089b-23b6-7d0ee2544ec5 [new,managed])
```

[testpk.zip](https://github.com/Haulmont/jmix-data/files/8106501/testpk.zip)

**Comment by dtaimanov** [comment]
It seems to be liquibase generation platform, created issue JST-2660.
